### PR TITLE
added getuserbyid() to sharepointclient

### PR DESCRIPTION
**Pull request by cjgehinscott**
added getuserbyid() to return user info from an ID

### CODE REVIEW

**Comment by cjgehinscott** [comment]
@marcote Glad I could contribute!

I just added the unit test. Please let me know if you need anything else from me.

Best!

**Comment by marcote** [comment]
There is a local.properties file that shouldn't be part of the PR. 
Also, I'm seeing some references to JUnit, and I think they're not required. The intent is correct, but I think you I lost you in the Test part. 

Two options :
*  Try to remove all the added dependencies and/or imports into https://github.com/cjgehinscott/Office-365-SDK-for-Android/commit/cc4d3140ca203ecceaf5a3b7e8becc4624a6282d and see if you can mimic the other tests. We use a GUI test runner which is the app itself, not JUnit, maybe that was the confusing part.
*  Remove the Test from the PR and I will add it later ASAP. Most likely on Monday.

Thanks again

**Comment by cjgehinscott** [comment]
@marcote I removed the imports.  They snuck in there on me by accident from the autocomplete/import.  I also removed the local.properties file.  Let me know if that will work.

Best!

**Comment by marcote** [comment]
@cjgehinscott just a heads up to tell you I haven't forgotten about this. Just to much work on my plate.

**Comment by cjgehinscott** [comment]
@marcote No problem.  I have been working with a Microsoft Consultant on another problem and he is going to be doing a pull request for something else we found that will be useful.  I'm glad this library is getting better and better.

**Comment by marcote** [comment]
@cjgehinscott I had to remove the test, but I was able to merge your contribution to dev branch. You can see it here: https://github.com/OfficeDev/Office-365-SDK-for-Android/commit/35c69c203e2598aec3924583f4ce5286a361e849 .

Thank you!

**Pull request closed without merging**
